version: '3'
services:
  mongo:
    image: mongo
    volumes:
    - mongodbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example1
    ports: 
      - "27017:27017"
    networks:
      backend:
        aliases:
          - mongo
    command: mongod --replSet "rs" --auth --bind_ip_all

  express:
    image: "node:alpine"
    working_dir: /usr/src/app
    volumes:
      - ./data/express:/usr/src/app
    depends_on:
      - "mongo"
    networks:
      backend:
        aliases:
          - express
      frontend:
        aliases:
          - express
    command: "npm start"
    labels:
       - traefik.enable=true
       - "traefik.frontend.rule=PathPrefix:/api;Host:robbo.xyz"
       - "traefik.port=9000"
       - "traefik.backend=express"
       - "traefik.frontend.priority=20"

  
  react:
    image: "robbof/react:v2"
    working_dir: /usr/src/my-app
    volumes:
      - ./data/react/my-app:/usr/src/my-app
    ports:
      - "3000:3000"
    depends_on:
      - "express"
    labels:
      - traefik.enable=true
      - "traefik.frontend.rule=Host:robbo.xyz"
      - "traefik.port=3000"
      - "traefik.frontend.passHostHeader=false"
      - "traefik.frontend.priority=10"

    networks: 
      frontend:
        aliases:
          - react
    command: "npm start"
  
  traefik:
    image: traefik:alpine
    ports: 
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./data/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/traefik/acme.json:/etc/traefik/acme/acme.json
    networks:
      backend:
        aliases:
          - traefik
      frontend:
        aliases:
          - traefik
    labels:
        - traefik.enable=true
        - "traefik.port=8080"
        - "traefik.frontend.rule=Path:/traefik"
        - "traefik.backend=traefikb_1"


  whoami:
    image: emilevauge/whoami
    labels:
      - traefik.enable.true
      - "traefik.frontend.rule=Host:whoami.docker.localhost"

volumes:
  mongodbdata:

networks:
  backend:
  frontend:
    # external: true